services:
    opensearch:
        container_name: buffalogs_opensearch
        image: opensearchproject/opensearch:latest
        hostname: opensearch
        environment:
            - node.name=buffalogs_opensearch
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - cluster.name=opensearch-cluster
            - DISABLE_SECURITY_PLUGIN=true 
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
            - "9600:9600"
        volumes:
            - opensearch_data:/usr/share/opensearch/data
        networks:
            - opensearch-net
            - buffalogs_network

    opensearch-dashboards:
        container_name: buffalogs_opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:latest
        hostname: opensearch-dashboards
        environment:
            OPENSEARCH_HOSTS: http://opensearch:9200
            DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
        ports:
            - "127.0.0.1:5601:5601"
        networks:
            - opensearch-net
            - buffalogs_network

volumes:
    opensearch_data:
        driver: local

networks:
    opensearch-net:
        driver: bridge
    buffalogs_network:
        external: true