services:
    buffalogs:
        volumes:
            - ./buffalogs:/opt/certego/buffalogs
    buffalogs_celery:
        volumes:
            - ./buffalogs:/opt/certego/buffalogs

    buffalogs_celery_beat:
        volumes:
            - ./buffalogs:/opt/certego/buffalogs

    buffalogs_postgres:
        ports:
            - "127.0.0.1:5433:5432"
    
    buffalogs_rabbitmq:
        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"