services:
    elasticsearch:
        container_name: buffalogs_elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
        hostname: elasticsearch
        environment: 
            - node.name=buffalogs_elastic
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - discovery.type=single-node
            - cluster.routing.allocation.disk.watermark.low=99%
            - cluster.routing.allocation.disk.watermark.high=99%
            - cluster.routing.allocation.disk.watermark.flood_stage=99%
            - xpack.security.enabled=true   # Enable security
        ulimits:
            memlock: 
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        healthcheck:
            test: curl -XGET 'localhost:9200/_cluster/health?wait_for_status=yellow&timeout=180s&pretty'

    kibana:
        container_name: buffalogs_kibana
        image: docker.elastic.co/kibana/kibana:7.17.27
        hostname: kibana
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            ELASTICSEARCH_USERNAME: kibana_system
            ELASTICSEARCH_PASSWORD: 3kwnLlcSHnJYRDh2kWi9  # Secure password storage
        depends_on:
            - elasticsearch
        ports:
            - "127.0.0.1:5601:5601"
        healthcheck:
            test: curl -fs http://localhost:5601/

volumes:
    elasticsearch_data:
        driver: local
